% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={HW2-Trinath Sai Subhash Reddy-Pittala},
  pdfauthor={Subhash},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{HW2-Trinath Sai Subhash Reddy-Pittala}
\author{Subhash}
\date{2023-03-05}

\begin{document}
\maketitle

\hypertarget{simple-linear-regression}{%
\section{Simple linear regression}\label{simple-linear-regression}}

A. Write the regression equation in both forms (i.e., with and without
error terms) as shown in class.

\[
arrivaldelay = \beta_{0} + \beta_{1} * depdelay + \epsilon
\] \[
\hat{arrivaldelay} = \hat{\beta_{0}} + \hat{\beta_{1}} * depdelay
\]

B. Load the flights dataset from the nycflights13 package using the
library(``nycflights13'') function (you need to have already installed
this package on your computer using the
install.packages(``nycflights13'') command in R).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load the nycflights13 library}
\FunctionTok{library}\NormalTok{(nycflights13)}
\NormalTok{flights}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 336,776 x 19
##     year month   day dep_time sched_de~1 dep_d~2 arr_t~3 sched~4 arr_d~5 carrier
##    <int> <int> <int>    <int>      <int>   <dbl>   <int>   <int>   <dbl> <chr>  
##  1  2013     1     1      517        515       2     830     819      11 UA     
##  2  2013     1     1      533        529       4     850     830      20 UA     
##  3  2013     1     1      542        540       2     923     850      33 AA     
##  4  2013     1     1      544        545      -1    1004    1022     -18 B6     
##  5  2013     1     1      554        600      -6     812     837     -25 DL     
##  6  2013     1     1      554        558      -4     740     728      12 UA     
##  7  2013     1     1      555        600      -5     913     854      19 B6     
##  8  2013     1     1      557        600      -3     709     723     -14 EV     
##  9  2013     1     1      557        600      -3     838     846      -8 B6     
## 10  2013     1     1      558        600      -2     753     745       8 AA     
## # ... with 336,766 more rows, 9 more variables: flight <int>, tailnum <chr>,
## #   origin <chr>, dest <chr>, air_time <dbl>, distance <dbl>, hour <dbl>,
## #   minute <dbl>, time_hour <dttm>, and abbreviated variable names
## #   1: sched_dep_time, 2: dep_delay, 3: arr_time, 4: sched_arr_time,
## #   5: arr_delay
\end{verbatim}

C. Run a simple linear regression model using the lm() function and save
the model as M1.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{M1 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(arr\_delay }\SpecialCharTok{\textasciitilde{}}\NormalTok{ dep\_delay, }\AttributeTok{data =}\NormalTok{ flights)}
\end{Highlighting}
\end{Shaded}

D. Output the elements of M1 using the summary() function.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(M1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = arr_delay ~ dep_delay, data = flights)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -107.587  -11.005   -1.883    8.938  201.938 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(>|t|)    
## (Intercept) -5.8994935  0.0330195  -178.7   <2e-16 ***
## dep_delay    1.0190929  0.0007864  1295.8   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 18.03 on 327344 degrees of freedom
##   (9430 observations deleted due to missingness)
## Multiple R-squared:  0.8369, Adjusted R-squared:  0.8369 
## F-statistic: 1.679e+06 on 1 and 327344 DF,  p-value: < 2.2e-16
\end{verbatim}

E. Explain the regression coefficients (intercept and slope estimates)
in one sentence each. I want a ``common sense'' explanation, e.g., ``The
regression slope is AAA which denotes that the arrival delay changes by
AAA hours for every 1 hour increase in departure delay'' etc.

The regression slope is 1.02 which denotes that the arrival delay
increases by 1.02 hours for every 1 hour increase in departure delay.
Also, since intercept is -5.89, if departure delay for a flight is 0
then the arrival delay is -5.89.

F. Explain the Pr(\textgreater{} \textbar t\textbar) values for the two
coefficients and how they capture the uncertainty in the regression
coefficient estimates.

Pr(\textgreater{} \textbar t\textbar) are p-values for probability of
observing for T-statistic and deciding on Null hypothesis. Since for
both slope and intercept the values are small (\textless2e-16) indicates
that our estimates are significant hence eliminating null hypothesis and
indicating stronger corelation between arrival and departure delays.

G. Explain what the R2 numerical value indicates for this particular
model in one sentence.

R2 value is the amount of data which can fit the given distribution.
Here 83.69\% of data is fitting the distribution i.e, there is 83.69\%
of variability of Arrival delay is explained by the Departure delay.

\hypertarget{multiple-linear-regression}{%
\section{Multiple linear regression}\label{multiple-linear-regression}}

A. Write out the regression equations in both forms for this multiple
linear regression model.

\[
arrivaldelay = \beta_{0} + \beta_{1} * depdelay + \beta_{2} * schedarrtime + \beta_{3} * distance + \epsilon
\] \[
\hat{arrivaldelay} = \hat{\beta_{0}} + \hat{\beta_{1}} * depdelay + \hat{\beta_{2}} * schedarrtime + \hat{\beta_{3}} * distance
\]

B. Build the model in R using the lm() function and save this model as
M2.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{M2 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(arr\_delay }\SpecialCharTok{\textasciitilde{}}\NormalTok{ dep\_delay }\SpecialCharTok{+}\NormalTok{ sched\_arr\_time }\SpecialCharTok{+}\NormalTok{ distance, }\AttributeTok{data =}\NormalTok{ flights)}
\FunctionTok{summary}\NormalTok{(M2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = arr_delay ~ dep_delay + sched_arr_time + distance, 
##     data = flights)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -107.983  -11.023   -2.018    8.668  205.024 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(>|t|)    
## (Intercept)    -1.825e+00  1.082e-01  -16.86   <2e-16 ***
## dep_delay       1.020e+00  7.926e-04 1286.88   <2e-16 ***
## sched_arr_time -9.553e-04  6.393e-05  -14.94   <2e-16 ***
## distance       -2.501e-03  4.271e-05  -58.55   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 17.92 on 327342 degrees of freedom
##   (9430 observations deleted due to missingness)
## Multiple R-squared:  0.8387, Adjusted R-squared:  0.8387 
## F-statistic: 5.675e+05 on 3 and 327342 DF,  p-value: < 2.2e-16
\end{verbatim}

C. Explain the regression constant and the different regression
coefficients in 1 precise sentence each. Note that each regression
coefficient has to be explained also in terms of keeping all the other
IVs constant. Also, explain how the regression coefficient for
dep\_delay changed between M1 and M2.

Regression constant (\(\beta_{0}\)) is the intercept of the given linear
regression equation i.e, value for which the other 3 IV's are zeroes.

\(\beta_{1}\) is the regression coefficient for the Independent variable
Departure Delay i.e, the differential of Departure delay vs arrival
delay when other IV's are constant.

\(\beta_{2}\) is the regression coefficient for the Independent variable
Scheduled Arrived Time i.e, the differential of Scheduled Arrived Time
vs arrival delay when other IV's are constant.

\(\beta_{3}\) is the regression coefficient for the Independent variable
Distance i.e, the differential of Distance vs arrival delay when other
IV's are constant.

The \(\beta_{1}\) is same in M1 and M2 because addition of Scheduled
Arrived Time and Distance did not influence the relation between Arrival
Delay and Departure delay in this particular case.

D. Comment on the uncertainty in each of the regression coefficient
estimates based on the Pr(\textgreater{} \textbar t\textbar) values in
the R output.

Pr(\textgreater{} \textbar t\textbar) are p-values for probability of
observing for T-statistic and deciding on Null hypothesis. Since for
both slope and intercept the values are small (\textless2e-16) indicates
that our estimates are significant hence eliminating null hypothesis and
indicating corelation between arrival and departure delays, Scheduled
Arrived Time, Distance.

E. Comment on the change in R2 value compared to M1.

R2 value increased from 83.69 percent to 83.87 percent indicating that
data is fitting the M2 better than M1.

\hypertarget{multiple-linear-regression-with-a-qualitative-variable}{%
\section{Multiple linear regression with a qualitative
variable}\label{multiple-linear-regression-with-a-qualitative-variable}}

A. Create a new variable called carrierAA using the mutate() function.
This variable is TRUE if the carrier is AA, else it is FALSE.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{flights }\OtherTok{\textless{}{-}} \FunctionTok{mutate}\NormalTok{(flights, }\AttributeTok{carrierAA =} \FunctionTok{ifelse}\NormalTok{(carrier }\SpecialCharTok{==} \StringTok{"AA"}\NormalTok{,}
    \ConstantTok{TRUE}\NormalTok{, }\ConstantTok{FALSE}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

B. Build a model M3 that predicts arr\_delay based on this dichotomous
variable carrierAA.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{M3 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(arr\_delay }\SpecialCharTok{\textasciitilde{}}\NormalTok{ carrierAA, }\AttributeTok{data =}\NormalTok{ flights)}
\FunctionTok{summary}\NormalTok{(M3)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = arr_delay ~ carrierAA, data = flights)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
##  -93.6  -23.6  -11.6    7.4 1264.4 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(>|t|)    
## (Intercept)    7.60170    0.08203   92.67   <2e-16 ***
## carrierAATRUE -7.23741    0.26257  -27.56   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 44.58 on 327344 degrees of freedom
##   (9430 observations deleted due to missingness)
## Multiple R-squared:  0.002316,   Adjusted R-squared:  0.002313 
## F-statistic: 759.8 on 1 and 327344 DF,  p-value: < 2.2e-16
\end{verbatim}

C. Explain what the regression slope and the regression constant for
this model mean by writing out the regression equation in the predictive
form. Note that TRUE is evaluated as 1, and FALSE as 0 by R in a
numerical context. Also, find the predicted arr\_delay for flights that
are AA, and flights that are not AA, based on the regression equation
and the regression coefficients calculated from R. \[
\hat{arrivaldelay} = \hat{\beta_{0}} + \hat{\beta_{1}} * carrierAA
\] \(\beta_{0}\) is regression Constant which describes the arrival
delay when flight is not American Airlines and \(\beta_{1}\) is
Regression Coefficient for carrierAA which describes the differential of
arrival delay when flight is American Airlines

Arrival Delay estimate for CarrierAA is +7.60170-7.23741(1) = 0.36429

Arrival Delay estimate for not CarrierAA is +7.60170-7.23741(0) =
7.60170

D. Now, build a model M4 \textless- lm(arr\_delay \textasciitilde{}
carrier, data = flights). Run the summary(M4) and comment on what R has
done in terms of the regression coefficients.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{M4 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(arr\_delay }\SpecialCharTok{\textasciitilde{}}\NormalTok{ carrier, }\AttributeTok{data =}\NormalTok{ flights)}
\FunctionTok{summary}\NormalTok{(M4)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = arr_delay ~ carrier, data = flights)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
##  -87.76  -23.64  -11.46    7.44 1278.92 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)   7.3797     0.3368  21.908  < 2e-16 ***
## carrierAA    -7.0154     0.4182 -16.775  < 2e-16 ***
## carrierAS   -17.3106     1.6974 -10.198  < 2e-16 ***
## carrierB6     2.0783     0.3870   5.370 7.87e-08 ***
## carrierDL    -5.7353     0.3932 -14.585  < 2e-16 ***
## carrierEV     8.4168     0.3897  21.598  < 2e-16 ***
## carrierF9    14.5410     1.7306   8.402  < 2e-16 ***
## carrierFL    12.7362     0.8553  14.891  < 2e-16 ***
## carrierHA   -14.2949     2.4189  -5.910 3.43e-09 ***
## carrierMQ     3.3951     0.4380   7.751 9.12e-15 ***
## carrierOO     4.5514     8.2328   0.553     0.58    
## carrierUA    -3.8217     0.3840  -9.953  < 2e-16 ***
## carrierUS    -5.2501     0.4609 -11.391  < 2e-16 ***
## carrierVX    -5.6152     0.7050  -7.965 1.66e-15 ***
## carrierWN     2.2695     0.5257   4.317 1.58e-05 ***
## carrierYV     8.1773     1.9289   4.239 2.24e-05 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 44.3 on 327330 degrees of freedom
##   (9430 observations deleted due to missingness)
## Multiple R-squared:  0.01502,    Adjusted R-squared:  0.01498 
## F-statistic: 332.9 on 15 and 327330 DF,  p-value: < 2.2e-16
\end{verbatim}

R has made 15 dummy variables to represent 16 variables (all carriers).
We can deduce the value of the 16th category from the values of the
other 15 dummy variables. If all the 15 dummy variables are set to 0
(FALSE), then it implies that the leftover is 16th variable.

E. Dummy variable coding: When a qualitative variable is included in a
regression model, R creates a series of variables called dummy
variables, each of which takes values TRUE or FALSE, similar to what we
did with carrierAA. Notice that there are 16 unique values for the
carrier variable in the dataset, and R creates 15 dummy variables for
the regression. Explain how this set of 15 dummy variables allows for
all 16 values in the original dataset to be represented. Hint: First
find the one carrier value that is not represented in the dummy variable
set. Then, notice the logic that when we want to represent the carrier
YV, we could set carrierYV = 1 (TRUE), and all other dummy variables
will have to be 0 (FALSE). Now, what happens when all the dummy
variables are set to 0?

In the dataset, there are 16 unique values for the carrier variable, but
only 15 dummy variables are created for the regression. This is because
we can deduce the value of the 16th category from the values of the
other 15 dummy variables. If all the 15 dummy variables are set to 0
(FALSE), then it implies that the 16th category (which is not
represented in the dummy variable set) is present.

F. Write out a regression equation that corresponds to the output of the
lm() function using the 15 dummy variables. Remember that these
variables mathematically can only take values 0 or 1.

\[
arr\ delay = 7.3797 + (-7.0154)  * carrierAA + (-17.3106) * carrierAS + ... + (8.1773) * carrierYV
\]

G. Explain what the regression constant and the different regression
coefficients mean in terms of predicted arr\_delay in this model. Notice
the regression constant corresponds to setting all variables in the
regression equation to 0, and hence corresponds to a particular carrier
(called the reference or the baseline value). This reference or baseline
can be chosen by the user but R automatically chooses a carrier to be
the baseline in this case. Similary a unit change in a dummy variable
corresponds to changing that variable from 0 to 1, which means changing
from the reference carrier to the carrier in question.

The predicted arr\_delay for each carrier can be calculated using the
regression equation:

\[
\hat{predicted\ arr\ delay} = \hat{\beta_{0}} + \hat{\beta_{1}} * carrierAA + \hat{\beta_{2}} * carrierAS + ... + \hat{\beta_{15}} * carrierYV
\]

Where: \(\beta_{0}\) is the intercept (7.3797) and 16th carrier (9E)
which is the reference carrier \(\beta_{1}\) to \(\beta_{15}\) are the
coefficients for each of the 15 carriers (AA, AS, B6, DL, EV, F9, FL,
HA, MQ, OO, UA, US, VX, WN, and YV) where each of them are either 0 or 1

H. Tabulate the predicted delay for each carrier based on this model
using the regression equation.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Create a data frame}
\NormalTok{res }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(M4)}\SpecialCharTok{$}\NormalTok{coefficients}
\FunctionTok{rownames}\NormalTok{(res)[}\DecValTok{1}\NormalTok{] }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\StringTok{"carrier9E"}\NormalTok{)}
\NormalTok{res[}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{] }\OtherTok{=}\NormalTok{ res[}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{] }\SpecialCharTok{+}\NormalTok{ res[}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{]}
\NormalTok{res[}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{] }\OtherTok{=}\NormalTok{ res[}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{+}\NormalTok{ res[}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{]}
\NormalTok{res }\OtherTok{=}\NormalTok{ res[, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{2}\NormalTok{]}
\FunctionTok{colnames}\NormalTok{(res)[}\DecValTok{1}\NormalTok{] }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\StringTok{"Arrival\_delay"}\NormalTok{)}
\FunctionTok{colnames}\NormalTok{(res)[}\DecValTok{2}\NormalTok{] }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\StringTok{"Standard\_Error"}\NormalTok{)}

\FunctionTok{kable}\NormalTok{(res)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lrr@{}}
\toprule()
& Arrival\_delay & Standard\_Error \\
\midrule()
\endhead
carrier9E & 7.3796692 & 0.3368478 \\
carrierAA & 0.3642909 & 0.7550460 \\
carrierAS & -9.9308886 & 2.0342434 \\
carrierB6 & 9.4579733 & 0.7238520 \\
carrierDL & 1.6443409 & 0.7300918 \\
carrierEV & 15.7964311 & 0.7265418 \\
carrierF9 & 21.9207048 & 2.0674396 \\
carrierFL & 20.1159055 & 1.1921315 \\
carrierHA & -6.9152047 & 2.7557636 \\
carrierMQ & 10.7747334 & 0.7748456 \\
carrierOO & 11.9310345 & 8.5696239 \\
carrierUA & 3.5580111 & 0.7208096 \\
carrierUS & 2.1295951 & 0.7977351 \\
carrierVX & 1.7644644 & 1.0418483 \\
carrierWN & 9.6491199 & 0.8625789 \\
carrierYV & 15.5569853 & 2.2657375 \\
\bottomrule()
\end{longtable}

\hypertarget{multiple-regression-with-both-quantitative-and-qualitative-variables}{%
\section{Multiple regression with both quantitative and qualitative
variables}\label{multiple-regression-with-both-quantitative-and-qualitative-variables}}

A. Build a model M5 in R that has all the variables in M2 as well as the
carrier variable.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{M5 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(arr\_delay }\SpecialCharTok{\textasciitilde{}}\NormalTok{ dep\_delay }\SpecialCharTok{+}\NormalTok{ sched\_arr\_time }\SpecialCharTok{+}\NormalTok{ distance }\SpecialCharTok{+}
\NormalTok{    carrierAA, }\AttributeTok{data =}\NormalTok{ flights)}
\FunctionTok{summary}\NormalTok{(M5)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = arr_delay ~ dep_delay + sched_arr_time + distance + 
##     carrierAA, data = flights)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -108.054  -11.023   -2.014    8.653  204.683 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(>|t|)    
## (Intercept)    -1.741e+00  1.083e-01  -16.08   <2e-16 ***
## dep_delay       1.020e+00  7.926e-04 1286.40   <2e-16 ***
## sched_arr_time -9.529e-04  6.390e-05  -14.91   <2e-16 ***
## distance       -2.398e-03  4.306e-05  -55.70   <2e-16 ***
## carrierAATRUE  -1.939e+00  1.065e-01  -18.21   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 17.91 on 327341 degrees of freedom
##   (9430 observations deleted due to missingness)
## Multiple R-squared:  0.8389, Adjusted R-squared:  0.8389 
## F-statistic: 4.262e+05 on 4 and 327341 DF,  p-value: < 2.2e-16
\end{verbatim}

B. Explain the regression coefficients including the regression
constant. In this case, the slopes due to the quantitative variables do
not depend on the carrier. The effect of each carrier is to add a fixed
predicted delay when all the quantitative variables are held constant.

\[
arrivaldelay = \beta_{0} + \beta_{1} * depdelay + \beta_{2} * schedarrtime + \beta_{3} * distance + \beta_{4} * carrier + \epsilon
\] \[
\hat{arrivaldelay} = \hat{\beta_{0}} + \hat{\beta_{1}} * depdelay + \hat{\beta_{2}} * schedarrtime + \hat{\beta_{3}} * distance + \hat{\beta_{4}} * carrier
\]

Regression coefficients (\(\beta_{i}\)) quantifies the amount of
correlation (the differential) between the Arrival delay with Departure
Delay, Scheduled Arrival Time, Distance, and Carrier.

Regression Constant (\(\beta_{0}\)) is the Baseline Arrival Delay given
all the other quantitative variables are constant and equal to zero.

C. Explain the R2 value for M5, and explain how this model compares to
models M1, M2, and M4.

R2 for M5 is 0.8389. Its highest of M1, M2 and M4 suggesting a better
fit to a Linear regression model.

\end{document}
