---
title: "Buffer for Project"
author: "Subhash"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
ggplot(my_outliers, aes(x = realSum, y = dist)) + 
  geom_point(alpha = 0.5) + 
  theme(axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14))
```

```{r}
ggplot(my_outliers, aes(x = realSum, fill = cleanliness_rating, group = cleanliness_rating)) + 
  geom_density(alpha = 0.5) + 
  theme(axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14)) + facet_wrap(~cleanliness_rating)
```

```{r}
ggplot(my_outliers, aes(x = realSum, fill = room_shared, group = room_shared)) + 
  geom_density(alpha = 0.5) + 
  theme(axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14))
```

```{r}
ggplot(my_outliers, aes(x = realSum, fill = room_private, group = room_private)) + 
  geom_histogram(alpha = 0.5, bins = 20) + 
  theme(axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14))
```

```{r}
ggplot(my_outliers, aes(x = realSum, fill = multi, group = multi)) + 
  geom_histogram(alpha = 0.5, bins = 20) + 
  theme(axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14))
```


```{r}
ggpairs(my_data[c("realSum","room_type","person_capacity","host_is_superhost","multi","biz","cleanliness_rating"
                  ,"guest_satisfaction_overall","bedrooms","dist","metro_dist"
                  ,"attr_index_norm","rest_index","city_day")], cardinality = 20, cardinality_threshold = 999)
```

```{r}
ggpairs(my_data[c("realSum","dist","metro_dist"
                  ,"attr_index_norm","rest_index_norm","city_day")], cardinality = 20, cardinality_threshold = 999)
```

```{r}
ggpairs(my_data_filtered[c("realSum","dist","metro_dist"
                  ,"attr_index_norm","rest_index_norm","city_day")], cardinality = 20, cardinality_threshold = 999)
```

```{r}
ggplot() +
  geom_point(data = my_data_filtered, aes(x = attr_index_norm, y = rest_index_norm, color = "Filtered Data"), alpha = 0.4) +
  geom_point(data = my_outliers, aes(x = attr_index_norm, y = rest_index_norm, color = "Outliers"), alpha = 0.4) +
  scale_color_manual(values = c("Filtered Data" = "blue", "Outliers" = "red"))

ggplot() +
  geom_point(data = my_data_filtered, aes(x = attr_index_norm, y = rest_index_norm, color = "Filtered Data"), alpha = 0.4) +
  geom_point(data = my_outliers, aes(x = attr_index_norm, y = rest_index_norm, color = "Outliers"), alpha = 0.4) +
  scale_color_manual(values = c("Filtered Data" = "blue", "Outliers" = "red")) +
  facet_wrap(~city_day)

ggplot() +
  geom_point(data = my_data, aes(x = attr_index_norm, y = rest_index_norm, color = "Filtered Data"), alpha = 0.4) +
  geom_point(data = my_outliers, aes(x = attr_index_norm, y = rest_index_norm, color = "Outliers"), alpha = 0.4) +
  scale_color_manual(values = c("Filtered Data" = "blue", "Outliers" = "red"))

ggplot() +
  geom_point(data = my_data, aes(x = attr_index_norm, y = rest_index_norm, color = "Filtered Data"), alpha = 0.4) +
  geom_point(data = my_outliers, aes(x = attr_index_norm, y = rest_index_norm, color = "Outliers"), alpha = 0.4) +
  scale_color_manual(values = c("Filtered Data" = "blue", "Outliers" = "red")) +
  facet_wrap(~city_day)
```


```{r}
my_data[c("realSum","room_type","person_capacity","host_is_superhost","multi","biz","cleanliness_rating"
                  ,"guest_satisfaction_overall","bedrooms","dist","metro_dist"
                  ,"attr_index_norm","rest_index","city_day")]
```


### Boxplot of City vs Guest Satisfaction

```{r}
ggplot(my_data_filtered, aes(x = reorder(city_day, guest_satisfaction_overall, FUN=median), y = guest_satisfaction_overall, fill = city_day)) + 
  geom_boxplot() +
  coord_flip() + 
  theme(legend.key.height = unit(0.5, "cm"),
        legend.key.size = unit(1, "lines"))
```